<a href="https://colab.research.google.com/github/merriekay/CS167-Notebook-3/blob/main/Notebook3_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook #3
**Due**: 9/28/21 by 11:59 pm.

**Name**: 

Be sure to start with the subset that you used in Notebook #2.
- Only rows with 'Fuel Type' as `regular`.
- the `displ`, `cylinders`, `year`, and `comb08` columns.

In [6]:
import pandas
import numpy
from google.colab import drive 
drive.mount('/content/drive')
data = pandas.read_csv('/content/drive/MyDrive/CS167/datasets/vehicles.csv')
data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (70,71,72,73,74,76,79) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   barrels08  barrelsA08  charge120  ...  phevCity  phevHwy  phevComb
0  15.695714         0.0        0.0  ...         0        0         0
1  29.964545         0.0        0.0  ...         0        0         0
2  12.207778         0.0        0.0  ...         0        0         0
3  29.964545         0.0        0.0  ...         0        0         0
4  17.347895         0.0        0.0  ...         0        0         0

[5 rows x 83 columns]

In [2]:
# Make your subset here.

## Exercise #1

Modify your code from Notebook #2/class to use cross validation. 
- Don't forget that you're doing **regression**--pay attention to what you need to change to make this do regression rather than classification
- make sure to implement an appropriate **regression metric** - you can use any of the ones we talked about in class, but code it up yourself. Avoid using for loops in your calculation, they're unnecesary.
- The sample code uses the word 'classification' a lot in the name of things... make sure you use the word 'regression' instead if you write similar functions.
- your code should be clear and readable.

In [ ]:
#your code here

# Exercise #2
Use approximately the first 500 rows in the shuffled set as testing data. Feel free to use fewer examples in your testing set-- particulary if it takes a long time ro run on your computer (more than 1 min or so).

In [3]:
#your code here

## Exercise #3
Test your model using several different values of k and **graphically show the results.**

In [4]:
# your code here

## Exercise #4
Run the code you wrote in Exercise #3 for different splits of the data -- varying the number of elements in the testing data and/or different values for the `random_state`.

In [5]:
# your code here

# Exercise #5
What conclusions can you draw about the best number for k for the kNN algorithm for this dataset? Use a text cell to explain your conclusions in a couple sentences.